---
  - hosts: all
    become: True
    gather_facts: True
    tasks:
       - name: Installing package samba on webserver nodes
         yum:
           name: samba
           state: present
         when: inventory_hostname in groups['web']

       - name: Installing package nfs-tils on prod server
         yum:
            name: nfs-utils
            state: present
         when: inventory_hostname in groups['prod']
